
service: lambda-norma

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  fetch:
    handler: functions/fetch.handler
  decode:
    handler: functions/decode.handler
  dec:
    handler: functions/dec.handler
  hasNextInstruction:
    handler: functions/hasNextInstruction.handler

stepFunctions:
  validate: true
  stateMachines:
    lambdaNormaFn:
      name: lambdaNormaStateMachine
      definition:
        Comment: "NORMA-like machine simulator"
        StartAt: Fetch
        States:
          Fetch:
            Type: Task
            Resource:
              Fn::GetAtt: [fetch, Arn]
            Next: Decode
          Decode:
            Type: Task
            Resource:
              Fn::GetAtt: [decode, Arn]
            Next: Execute
          Execute:
            Type: Choice
            Choices:
              - Variable: "$.body.decoded.inst"
                StringEquals: "dec"
                Next: dec
          dec:
            Type: Task
            Resource:
              Fn::GetAtt: [dec, Arn]
            Next: VerifyNextInstruction
          VerifyNextInstruction:
            Type: Task
            Resource:
              Fn::GetAtt: [hasNextInstruction, Arn]
            Next: HasNextInstruction?
          HasNextInstruction?:
            Type: Choice
            Choices:
              - Variable: "$.body.hasNextInst"
                BooleanEquals: false
                Next: Halt
          Halt:
            Type: Pass
            End: true